import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/page";
import Footer from "./components/Footer/page";
// import { Provider } from "react-redux";
import store from "./redux/store";
import dynamic from "next/dynamic";
const Provider = dynamic(() => import('./storeProvider'), {
  ssr: false, // Optionally disable server-side rendering if necessary
});
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Apples",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider >
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
